name: Jor3a-Ti9niya-RDP-Linux

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Install XRDP and Desktop Environment
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y xrdp xfce4 xfce4-goodies dbus-x11
        echo xfce4-session > ~/.xsession
        sudo systemctl enable xrdp
        sudo systemctl restart xrdp

    - name: Configure User and Firewall
      run: |
        # Create user with password
        sudo useradd -m -s /bin/bash ubuntuuser
        echo "ubuntuuser:admin@123" | sudo chpasswd
        sudo usermod -aG sudo ubuntuuser
        
        # Configure firewall
        sudo ufw allow 3389/tcp
        sudo ufw --force enable

    - name: Install Playit Agent
      run: |
        curl -Lo playit https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-amd64
        chmod +x playit
        sudo mv playit /usr/local/bin/

    - name: Start Playit Tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }}
      run: |
        nohup playit --secret $PLAYIT_AUTH_KEY > playit.log 2>&1 &
        echo "Playit tunnel started. Check logs at playit.log"

    - name: Keep Runner Alive
      run: |
        # Maintain connection for 6 hours
        sleep 21600
