name: Jor3a-Ti9niya-RDP-Linux

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Install XRDP and Desktop Environment
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y xrdp xfce4 xfce4-goodies dbus-x11
        echo xfce4-session > ~/.xsession
        sudo systemctl enable xrdp
        sudo systemctl restart xrdp

    - name: Configure User and Firewall
      run: |
        # Create user with password
        sudo useradd -m -s /bin/bash ubuntuuser
        echo "ubuntuuser:admin@123" | sudo chpasswd
        sudo usermod -aG sudo ubuntuuser
        
        # Configure firewall
        sudo ufw allow 3389/tcp
        sudo
