name: Jor3a-Ti9niya-RDP

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: macos-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Download and Install Playit
      run: |
        curl -L -o ~/playit "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-macos-x86_64"
        chmod +x ~/playit
        
    - name: Enable macOS Screen Sharing
      run: |
        # Enable Remote Desktop
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
          -activate -configure -access -on \
          -privs -all -restart -agent -clientopts -setmenuextra -menuextra no
        
        # Set password for current user
        sudo dscl . -passwd /Users/runner admin@123

        # Enable firewall exceptions (if needed)
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/MacOS/ARDAgent
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblockapp /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/MacOS/ARDAgent

    - name: Start Playit and Maintain Session
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }}
      run: |
        # Start Playit agent with authentication key
        nohup ~/playit --secret $PLAYIT_AUTH_KEY > ~/playit.log 2>&1 &
        
        # Keep runner active for 6 hours (21600 seconds)
        sleep 21600
