name: Ubuntu-RDP-Fixed

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: ubuntu-latest

    steps:
    - name: Configure XServer and Display Manager
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
          xrdp \
          xfce4 \
          xfce4-session \
          xserver-xorg-core \
          xserver-xorg-legacy \
          xorgxrdp \
          xvfb \
          lightdm \
          --no-install-recommends

        # Configure virtual display
        echo "allowed_users=anybody" | sudo tee /etc/X11/Xwrapper.config
        echo "[LightDM]" | sudo tee /etc/lightdm/lightdm.conf.d/50-xrdp.conf
        echo "display-setup-script=/usr/bin/xvfb-run" | sudo tee -a /etc/lightdm/lightdm.conf.d/50-xrdp.conf

    - name: Configure XRDP Environment
      run: |
        # Create proper XRDP session configuration
        sudo tee /etc/xrdp/startwm.sh <<'EOL'
        #!/bin/sh
        export XDG_CONFIG_DIRS="/etc/xdg:/etc/xdg/xdg-xubuntu"
        export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus"
        export DISPLAY=:0
        . /etc/X11/Xsession
        xfce4-session
        EOL
        sudo chmod +x /etc/xrdp/startwm.sh

    - name: Setup User and Services
      run: |
        # Create user with password
        sudo useradd -m -s /bin/bash ubuntuuser
        echo "ubuntuuser:admin@123" | sudo chpasswd
        sudo usermod -aG sudo ubuntuuser

        # Configure permissions
        sudo chown -R ubuntuuser:ubuntuuser /home/ubuntuuser
        sudo chmod 755 /home/ubuntuuser

        # Start virtual display and services
        sudo Xvfb :0 -screen 0 1280x720x24 &
        sudo systemctl restart dbus
        sudo systemctl restart lightdm
        sudo systemctl restart xrdp
        sleep 5  # Wait for services to initialize

    - name: Install Playit Agent
      run: |
        curl -Lo playit https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-amd64
        chmod +x playit
        sudo mv playit /usr/local/bin/

    - name: Start Playit Tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }}
      run: |
        nohup playit --secret $PLAYIT_AUTH_KEY > playit.log 2>&1 &
        echo "Playit tunnel started. Check logs at playit.log"
        sleep 10

    - name: Maintain Connection
      run: |
        sleep 21600  # 6 hours
