name: Ubuntu-RDP-Setup

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Install XRDP and Desktop Environment
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
          xrdp \
          xfce4 \
          xfce4-goodies \
          xfce4-session \
          dbus-x11 \
          lightdm \
          xserver-xorg-core
        
        # Configure Xsession
        echo xfce4-session > ~/.xsession
        sudo cp ~/.xsession /etc/skel/
        sudo sed -i 's/^allowed_users=.*/allowed_users=anyone/' /etc/X11/Xwrapper.config
        
        # Set default session for XRDP
        sudo echo "xfce4-session" | sudo tee /etc/xrdp/startwm.sh
        sudo systemctl restart xrdp

    - name: Configure User and Services
      run: |
        # Create user with password
        sudo useradd -m -s /bin/bash ubuntuuser
        echo "ubuntuuser:admin@123" | sudo chpasswd
        sudo usermod -aG sudo ubuntuuser
        
        # Ensure proper permissions
        sudo chown ubuntuuser:ubuntuuser /home/ubuntuuser/.xsession
        
        # Configure firewall
        sudo ufw allow 3389/tcp
        sudo ufw --force enable

    - name: Install Playit Agent
      run: |
        curl -Lo playit https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-amd64
        chmod +x playit
        sudo mv playit /usr/local/bin/

    - name: Start Services
      run: |
        sudo systemctl restart lightdm
        sudo systemctl restart xrdp

    - name: Start Playit Tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }}
      run: |
        nohup playit --secret $PLAYIT_AUTH_KEY > playit.log 2>&1 &
        sleep 10  # Wait for tunnel initialization

    - name: Maintain Connection
      run: |
        sleep 21600  # 6 hours
