name: Ubuntu-RDP-Fixed

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: ubuntu-latest

    steps:
    - name: Install XFCE with D-Bus Configuration
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
          xrdp \
          xfce4 \
          xfce4-session \
          xfce4-goodies \
          xfconf \
          dbus-x11 \
          lightdm \
          xserver-xorg-core \
          --no-install-recommends

        # Configure D-Bus and environment
        sudo systemctl enable dbus
        sudo systemctl start dbus
        echo 'export XDG_CONFIG_DIRS="/etc/xdg/xdg-xubuntu:/etc/xdg:/etc"' | sudo tee -a /etc/environment
        echo 'export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus"' | sudo tee -a /etc/environment

    - name: Configure XRDP Session
      run: |
        # Create proper startwm.sh configuration
        sudo cp /etc/xrdp/startwm.sh /etc/xrdp/startwm.sh.bak
        sudo tee /etc/xrdp/startwm.sh > /dev/null <<'EOL'
        #!/bin/sh
        if [ -r /etc/default/locale ]; then
          . /etc/default/locale
          export LANG LANGUAGE
        fi
        export XDG_CONFIG_DIRS="/etc/xdg/xdg-xubuntu:/etc/xdg:/etc"
        export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus"
        . /etc/X11/Xsession
        xfce4-session
        EOL
        sudo chmod +x /etc/xrdp/startwm.sh

    - name: Configure User and Permissions
      run: |
        sudo useradd -m -s /bin/bash ubuntuuser
        echo "ubuntuuser:admin@123" | sudo chpasswd
        sudo usermod -aG sudo ubuntuuser
        sudo mkdir -p /home/ubuntuuser/.config/xfce4/xfconf
        sudo chown -R ubuntuuser:ubuntuuser /home/ubuntuuser

    - name: Finalize Setup
      run: |
        # Configure Xwrapper
        echo "allowed_users=anybody" | sudo tee /etc/X11/Xwrapper.config
        sudo systemctl restart lightdm
        sudo systemctl restart xrdp
        sudo systemctl restart dbus
        sudo ufw allow 3389/tcp
        sudo ufw --force enable

    - name: Install Playit Agent
      run: |
        curl -Lo playit https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-amd64
        chmod +x playit
        sudo mv playit /usr/local/bin/

    - name: Start Playit Tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }}
      run: |
        nohup playit --secret $PLAYIT_AUTH_KEY > playit.log 2>&1 &
        sleep 10

    - name: Maintain Connection
      run: |
        sleep 21600
